# Importing required library

In [1]:
import keras
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.layers import Dropout

Using TensorFlow backend.


In [2]:
# initalization CNN model
model=Sequential()

In [3]:
# adding convolutional layer
model.add(Convolution2D(32,3,3,activation='relu',input_shape=(225, 225, 3)))

D:\Python\Software\Anaconda_new1\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), activation="relu", input_shape=(225, 225,...)`
  


In [4]:
# adding maxpooling layer
model.add(MaxPooling2D(pool_size=(2,2)))

In [5]:
# flatten the resultant matrix
model.add(Flatten())

feeding the resultant flatten matrix into the dense fully connected layer

In [6]:
# first input layer
model.add(Dense(128,activation='relu',kernel_initializer='normal'))
# output layer
model.add(Dense(1,activation='sigmoid')) # as this is image classification problem so the output layer having sigmoid activation 
# function which will give output 0,1

In [7]:
# compiling the model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [8]:
from keras.preprocessing.image import ImageDataGenerator

In [9]:
train_gen=ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)

In [10]:
test_gen=ImageDataGenerator(rescale=1./255)

In [11]:
train_image=train_gen.flow_from_directory("D:\\Minor project college\\Datasets\\brain_tumor_dataset",target_size=(225, 225),batch_size=32,class_mode='binary')

Found 253 images belonging to 2 classes.


In [12]:
test_image=test_gen.flow_from_directory("D:\\Minor project college\\Datasets\\test_data",target_size=(225,225),batch_size=32,class_mode='binary')

Found 60 images belonging to 2 classes.


In [13]:
model.fit_generator(train_image,steps_per_epoch=253,epochs=1, validation_data=test_image, validation_steps=60)

Epoch 1/1
253/253 [==============================] - 320s 1s/step - loss: 0.8917 - accuracy: 0.7966 - val_loss: 0.1986 - val_accuracy: 0.9500


In [14]:
from keras.preprocessing import image
import numpy as np

In [18]:
sample_img=image.load_img("D:\\Minor project college\\Datasets\\no\\Y4.jpg",target_size=(225,225))

In [19]:
img=image.img_to_array(sample_img)

In [20]:
print(img)

[[[190. 190. 190.]
  [110. 110. 110.]
  [137. 137. 137.]
  ...
  [129. 129. 129.]
  [129. 129. 129.]
  [174. 174. 174.]]

 [[108. 108. 108.]
  [  5.   5.   5.]
  [ 11.  11.  11.]
  ...
  [  1.   1.   1.]
  [  1.   1.   1.]
  [125. 125. 125.]]

 [[139. 139. 139.]
  [  9.   9.   9.]
  [  0.   0.   0.]
  ...
  [  1.   1.   1.]
  [  1.   1.   1.]
  [131. 131. 131.]]

 ...

 [[127. 127. 127.]
  [  2.   2.   2.]
  [  4.   4.   4.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [130. 130. 130.]]

 [[127. 127. 127.]
  [  2.   2.   2.]
  [  4.   4.   4.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [130. 130. 130.]]

 [[137. 137. 137.]
  [ 42.  42.  42.]
  [ 51.  51.  51.]
  ...
  [ 49.  49.  49.]
  [ 48.  48.  48.]
  [138. 138. 138.]]]


In [21]:
img=np.expand_dims(img,axis=0) # reshaping the image

In [22]:
print(img)

[[[[190. 190. 190.]
   [110. 110. 110.]
   [137. 137. 137.]
   ...
   [129. 129. 129.]
   [129. 129. 129.]
   [174. 174. 174.]]

  [[108. 108. 108.]
   [  5.   5.   5.]
   [ 11.  11.  11.]
   ...
   [  1.   1.   1.]
   [  1.   1.   1.]
   [125. 125. 125.]]

  [[139. 139. 139.]
   [  9.   9.   9.]
   [  0.   0.   0.]
   ...
   [  1.   1.   1.]
   [  1.   1.   1.]
   [131. 131. 131.]]

  ...

  [[127. 127. 127.]
   [  2.   2.   2.]
   [  4.   4.   4.]
   ...
   [  0.   0.   0.]
   [  0.   0.   0.]
   [130. 130. 130.]]

  [[127. 127. 127.]
   [  2.   2.   2.]
   [  4.   4.   4.]
   ...
   [  0.   0.   0.]
   [  0.   0.   0.]
   [130. 130. 130.]]

  [[137. 137. 137.]
   [ 42.  42.  42.]
   [ 51.  51.  51.]
   ...
   [ 49.  49.  49.]
   [ 48.  48.  48.]
   [138. 138. 138.]]]]


In [27]:
prediction=model.predict(img)

In [28]:
prediction

array([[1.]], dtype=float32)

In [29]:
train_image.class_indices

{'no': 0, 'yes': 1}

In [30]:
if prediction[0]==1:
    print("brain tumor detected")
else:
    print("not found")

brain tumor detected


In [41]:
import os

In [45]:
output_path="D:\\Minor project college\\Image Found"
dir="D:\\Minor project college\\Datasets\\no\\Y4.jpg"

In [47]:
if(prediction[0]==1):
    listdir(output_path)

In [46]:
def listdir(dir):
    filename=os.listdir(dir)
    for file in filename:
        print('image found'+file)
        print('folder path'+os.path.abspath(os.path.join(dir,file)),sep='\n')